site_name: 클라우드 보안 아키텍처 문서화
theme:
  name: material
  language: ko
  palette: 
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo 
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs 
    - navigation.sections 
    - toc.follow  

nav:
  - Home: index.md
  - 침해사고 분석:
      - "Drizly": 01-incident/case-01-drizly.md
      - "Capital One": 01-incident/case-02-capitalone.md
      - "AWS Community AMI": 01-incident/case-ami.md
      - "Tesla": 01-incident/case-tesla.md
      - "Ubiquiti": 01-incident/case-ubiquiti.md
      - "Lastpass": 01-incident/case-lastpass.md
      - "Onus": 01-incident/case-onus.md
      - "Sisense": 01-incident/case-sisense.md
      - "KiranaPro": 01-incident/case-kiranapro.md
      - "Twilio": 01-incident/case-twilio.md
  - 인프라 분석:
      - "UNiDAYS": 02-infra/analysis-01-unidays.md
      - "MADworld": 02-infra/analysis-madworld.md
      - "Nintendo Systems": 02-infra/analysis-nintendosystem.md
      - "AMI Lineage": 02-infra/analysis-AmiLineage.md
  - 아키텍처 설계:
      - "바이브코딩 아키텍처 설계": 03-architecture/01-hobby.md
      - "소규모 아키텍처 설계": 03-architecture/02-startup.md
      - "중소규모 아키텍처 설계": 03-architecture/03-growth.md
      - "중규모 아키텍처 설계": 03-architecture/04-enterprise.md
      - "대규모 아키텍처 설계": 03-architecture/05-hyperscale.md